/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/telly.glb 
*/

//react
import React, { useRef, useEffect } from "react";

//r3f
import * as THREE from "three";
import { useThree, useFrame } from "@react-three/fiber";
import {
  useGLTF,
  useTexture,
  MeshReflectorMaterial,
  useVideoTexture,
} from "@react-three/drei";
import { MeshLambertMaterial } from "three";
import { degToRad } from "three/src/math/MathUtils.js";
import * as BufferGeometryUtils from "three/addons/utils/BufferGeometryUtils.js";

export function Tele({ setTVDialogOpen }) {
  const { scene, nodes } = useGLTF("/models/tele.glb");

  // console.log(scene);
  //access panel tex
  const accessPanelDiffuse = useTexture(
    "/textures/access-panel_Bake1_PBR_Diffuse.png"
  );
  const accessPanelNormal = useTexture(
    "/textures/access-panel_Bake1_PBR_Normal.png"
  );
  const accessPanelRoughness = useTexture(
    "/textures/access-panel_Bake1_PBR_Roughness.png"
  );
  //aerial tex
  const aerialDiffuse = useTexture("/textures/aerial_Bake1_PBR_Diffuse.png");
  const aerialNormal = useTexture("/textures/aerial_Bake1_PBR_Normal.png");
  const aerialRoughness = useTexture(
    "/textures/aerial_Bake1_PBR_Roughness.png"
  );
  //aerial holder tex
  const aerialHolderDiffuse = useTexture(
    "/textures/aerial-holder_Bake1_PBR_Diffuse.png"
  );
  const aerialHolderNormal = useTexture(
    "/textures/aerial-holder_Bake1_PBR_Normal.png"
  );
  const aerialHolderRoughness = useTexture(
    "/textures/aerial-holder_Bake1_PBR_Roughness.png"
  );
  //body tex
  const bodyDiffuse = useTexture("/textures/body_Bake1_PBR_Diffuse.png");
  const bodyNormal = useTexture("/textures/body_Bake1_PBR_Normal.png");
  const bodyRoughness = useTexture("/textures/body_Bake1_PBR_Roughness.png");
  //button bottom tex
  const buttonBottomDiffuse = useTexture(
    "/textures/button-bottom_Bake1_PBR_Diffuse.png"
  );
  const buttonBottomNormal = useTexture(
    "/textures/button-bottom_Bake1_PBR_Normal.png"
  );
  const buttonBottomRoughness = useTexture(
    "/textures/button-bottom_Bake1_PBR_Roughness.png"
  );
  //button top tex
  const buttonTopDiffuse = useTexture(
    "/textures/button-top_Bake1_PBR_Diffuse.png"
  );
  const buttonTopNormal = useTexture(
    "/textures/button-top_Bake1_PBR_Normal.png"
  );
  const buttonTopRoughness = useTexture(
    "/textures/button-top_Bake1_PBR_Roughness.png"
  );
  //button top tex
  const buttonsChannelDiffuse = useTexture(
    "/textures/buttons-channel_Bake1_PBR_Diffuse.png"
  );
  const buttonsChannelNormal = useTexture(
    "/textures/buttons-channel_Bake1_PBR_Normal.png"
  );
  const buttonsChannelRoughness = useTexture(
    "/textures/buttons-channel_Bake1_PBR_Roughness.png"
  );
  //dial guard tex
  const dialGuardDiffuse = useTexture(
    "/textures/dial-guard_Bake1_PBR_Diffuse.png"
  );
  const dialGuardNormal = useTexture(
    "/textures/dial-guard_Bake1_PBR_Normal.png"
  );
  const dialGuardRoughness = useTexture(
    "/textures/dial-guard_Bake1_PBR_Roughness.png"
  );
  //dial washers tex
  const dialWashersDiffuse = useTexture(
    "/textures/dial-washers_Bake1_PBR_Diffuse.png"
  );
  const dialWashersNormal = useTexture(
    "/textures/dial-washers_Bake1_PBR_Normal.png"
  );
  const dialWashersRoughness = useTexture(
    "/textures/dial-washers_Bake1_PBR_Roughness.png"
  );
  //dials tex
  const dialsDiffuse = useTexture("/textures/dials_Bake1_PBR_Diffuse.png");
  const dialsNormal = useTexture("/textures/dials_Bake1_PBR_Normal.png");
  const dialsRoughness = useTexture("/textures/dials_Bake1_PBR_Roughness.png");
  //screen housing tex
  // const screenHousingDiffuse = useTexture(
  //   "/textures/screen-housing_Bake1_PBR_Diffuse.png"
  // );

  const videoTexture = useVideoTexture("/textures/intersect-tv-video-test.mp4");
  const flippedVideoTexture = videoTexture;
  useEffect(() => {
    bodyDiffuse.flipY = false;
    bodyDiffuse.needsUpdate = true;
    bodyNormal.flipY = false;
    bodyNormal.needsUpdate = true;
    bodyRoughness.flipY = false;
    bodyRoughness.needsUpdate = true;
    aerialHolderDiffuse.flipY = false;
    aerialHolderDiffuse.needsUpdate = true;
    aerialHolderNormal.flipY = false;
    aerialHolderNormal.needsUpdate = true;
    aerialHolderRoughness.flipY = false;
    aerialHolderRoughness.needsUpdate = true;
  }, []);

  useEffect(() => {
    scene.traverse((child) => {
      if (child.isMesh) {
        const geometry = child.geometry;
        const merged = BufferGeometryUtils.mergeVertices(geometry);
        merged.computeVertexNormals();
        child.geometry = merged;
        // const merged = BufferGeometryUtils.mergeVertices(child.geometry);
        // merged.computeVertexNormals();
        // child.geometry = merged;
        // geometry.computeVertexNormals();
        // geometry.normalsNeedUpdate = true;
      }
    });
  }, [scene]);

  const ref = useRef(null);
  const start = Math.PI / 10;
  const end = -Math.PI / 10;
  const { pointer } = useThree();
  useFrame(() => {
    ref.current.rotation.y = -(start + (end - start)) * pointer.x;
  });

  const { camera } = useThree();
  useEffect(() => {
    camera.lookAt(0, -2, 0);
  }, [camera]);

  return (
    <>
      <group
        ref={ref}
        // onPointerOver={(e) => {
        //   e.stopPropagation();
        //   setTVDialogOpen(true);
        // }}
        // onPointerOut={(e) => {
        //   e.stopPropagation();
        //   setTVDialogOpen(false);
        // }}
        // ref={ref}
        position={[0, -2.6, 0]}
        rotation={[0, -Math.PI / 1, 0]}
        // {...props}
        // position={[0, -4, -2]}
        // rotation={[0, Math.PI * 1.8, 0]}
        dispose={null}
      >
        <mesh
          receiveShadow
          geometry={nodes["dial-washers_Baked"].geometry}
          material={nodes["dial-washers_Baked"].material}
        >
          <meshStandardMaterial
            map={dialWashersDiffuse}
            normalMap={dialWashersNormal}
            roughnessMap={dialWashersRoughness}
          />
        </mesh>
        <mesh
          receiveShadow
          geometry={nodes.body_Baked.geometry}
          material={nodes.body_Baked.material}
        >
          <meshStandardMaterial
            map={bodyDiffuse}
            normalMap={bodyNormal}
            roughnessMap={bodyRoughness}
            roughness={0.8}
          />
        </mesh>
        <mesh
          receiveShadow
          flatShading={false}
          geometry={nodes["screen-housing_Baked"].geometry}
          material={nodes["screen-housing_Baked"].material}
        >
          <MeshReflectorMaterial
            color={"#222222"}
            // distance={0.2}
            blur={[300, 300]} // Blur ground reflections (width, height), 0 skips blur
            mixBlur={1} // How much blur mixes with surface roughness (default = 1)
            mixStrength={1} // Strength of the reflections
            mixContrast={1} // Contrast of the reflections
            resolution={512} // Off-buffer resolution, lower=faster, higher=better quality, slower
            mirror={0.2} // Mirror environment, 0 = texture colors, 1 = pick up env colors
            depthScale={0} // Scale the depth factor (0 = no depth, default = 0)
            minDepthThreshold={0.2} // Lower edge for the depthTexture interpolation (default = 0)
            maxDepthThreshold={1} // Upper edge for the depthTexture interpolation (default = 0)
            depthToBlurRatioBias={0.25} // Adds a bias factor to the depthTexture before calculating the blur amount [blurFactor = blurTexture * (depthTexture + bias)]. It accepts values between 0 and 1, default is 0.25. An amount > 0 of bias makes sure that the blurTexture is not too sharp because of the multiplication with the depthTexture
            //distortion={1} // Amount of distortion based on the distortionMap texture
            //distortionMap={distortionTexture} // The red channel of this texture is used as the distortion map. Default is null
            reflectorOffset={2} // Offsets the virtual camera that projects the reflection. Useful when the reflective surface is some distance from the object's origin (default = 0)
          />
        </mesh>
        <mesh
          geometry={nodes.screen_Baked.geometry}
          material={nodes.screen_Baked.material}
          position={[0, 0, 0.02]}
          rotation={[0, 0, 0]}
          scale={[1, 1, 1]}
        >
          <meshBasicMaterial
            // color="orange"
            map={videoTexture}
            // emissive="orange" // the glow color
            // emissiveIntensity={60}
          />
        </mesh>
        {/*reflection*/}
        <mesh
          geometry={nodes.screen_Baked.geometry}
          material={nodes.screen_Baked.material}
          position={[0, 0.65, 5]}
          rotation={[0, degToRad(180), 0]}
          scale={[-0.8, 0.8, 1]}
        >
          <meshStandardMaterial
            color="#111"
            emissive="#ffffff"
            emissiveIntensity={200}
            emissiveMap={videoTexture}
          />
        </mesh>
        <mesh receiveShadow geometry={nodes["access-panel_Baked"].geometry}>
          <meshStandardMaterial
            map={accessPanelDiffuse}
            normalMap={accessPanelNormal}
            roughnessMap={accessPanelRoughness}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.aerial_Baked.geometry}
          material={nodes.aerial_Baked.material}
          position={[0.148, 0, 0]}
        >
          <meshStandardMaterial
            map={aerialDiffuse}
            normalMap={aerialNormal}
            roughnessMap={aerialRoughness}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["button-bottom_Baked"].geometry}
          material={nodes["button-bottom_Baked"].material}
        >
          <meshStandardMaterial
            map={buttonBottomDiffuse}
            normalMap={buttonBottomNormal}
            roughnessMap={buttonBottomRoughness}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["button-top_Baked"].geometry}
          material={nodes["button-top_Baked"].material}
        >
          <meshStandardMaterial
            map={buttonTopDiffuse}
            normalMap={buttonTopNormal}
            roughnessMap={buttonTopRoughness}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["buttons-channel_Baked"].geometry}
          material={nodes["buttons-channel_Baked"].material}
        >
          <meshStandardMaterial
            map={buttonsChannelDiffuse}
            normalMap={buttonsChannelNormal}
            roughnessMap={buttonsChannelRoughness}
          />
        </mesh>
        <mesh
          receiveShadow
          geometry={nodes["dial-guard_Baked"].geometry}
          material={nodes["dial-guard_Baked"].material}
        >
          <meshStandardMaterial
            map={dialGuardDiffuse}
            normalMap={dialGuardNormal}
            roughnessMap={dialGuardRoughness}
          />
        </mesh>
        <mesh
          castShadow
          geometry={nodes.dials_Baked.geometry}
          material={nodes.dials_Baked.material}
        >
          <meshStandardMaterial
            map={dialsDiffuse}
            normalMap={dialsNormal}
            roughnessMap={dialsRoughness}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["aerial-holder_Baked"].geometry}
          material={nodes["aerial-holder_Baked"].material}
          position={[1.55, 4.6, -3.616]}
          scale={[0.155, 0.531, 0.155]}
        >
          <meshStandardMaterial
            map={aerialHolderDiffuse}
            normalMap={aerialHolderNormal}
            roughnessMap={aerialHolderRoughness}
          />
        </mesh>
      </group>
    </>
  );
}

useGLTF.preload("/tele.glb");
