/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/telly.glb 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

export function Tele(props) {
  const { nodes, materials } = useGLTF("/models/tele.glb");

  //access panel tex
  const accessPanelDiffuse = useTexture(
    "/textures/access-panel_Bake1_PBR_Diffuse.png"
  );
  const accessPanelNormal = useTexture(
    "/textures/access-panel_Bake1_PBR_Normal.png"
  );
  const accessPanelRoughness = useTexture(
    "/textures/access-panel_Bake1_PBR_Roughness.png"
  );
  //aerial tex
  const aerialDiffuse = useTexture("/textures/aerial_Bake1_PBR_Diffuse.png");
  const aerialNormal = useTexture("/textures/aerial_Bake1_PBR_Normal.png");
  const aerialRoughness = useTexture(
    "/textures/aerial_Bake1_PBR_Roughness.png"
  );
  //aerial holder tex
  const aerialHolderDiffuse = useTexture(
    "/textures/aerial-holder_Bake1_PBR_Diffuse.png"
  );
  const aerialHolderNormal = useTexture(
    "/textures/aerial-holder_Bake1_PBR_Normal.png"
  );
  const aerialHolderRoughness = useTexture(
    "/textures/aerial-holder_Bake1_PBR_Roughness.png"
  );
  //body tex
  const bodyDiffuse = useTexture("/textures/body_Bake1_PBR_Diffuse.png");
  const bodyNormal = useTexture("/textures/body_Bake1_PBR_Normal.png");
  const bodyRoughness = useTexture("/textures/body_Bake1_PBR_Roughness.png");
  //button bottom tex
  const buttonBottomDiffuse = useTexture(
    "/textures/button-bottom_Bake1_PBR_Diffuse.png"
  );
  const buttonBottomNormal = useTexture(
    "/textures/button-bottom_Bake1_PBR_Normal.png"
  );
  const buttonBottomRoughness = useTexture(
    "/textures/button-bottom_Bake1_PBR_Roughness.png"
  );
  //button top tex
  const buttonTopDiffuse = useTexture(
    "/textures/button-top_Bake1_PBR_Diffuse.png"
  );
  const buttonTopNormal = useTexture(
    "/textures/button-top_Bake1_PBR_Normal.png"
  );
  const buttonTopRoughness = useTexture(
    "/textures/button-top_Bake1_PBR_Roughness.png"
  );
  //button top tex
  const buttonsChannelDiffuse = useTexture(
    "/textures/buttons-channel_Bake1_PBR_Diffuse.png"
  );
  const buttonsChannelNormal = useTexture(
    "/textures/buttons-channel_Bake1_PBR_Normal.png"
  );
  const buttonsChannelRoughness = useTexture(
    "/textures/buttons-channel_Bake1_PBR_Roughness.png"
  );
  //dial guard tex
  const dialGuardDiffuse = useTexture(
    "/textures/dial-guard_Bake1_PBR_Diffuse.png"
  );
  const dialGuardNormal = useTexture(
    "/textures/dial-guard_Bake1_PBR_Normal.png"
  );
  const dialGuardRoughness = useTexture(
    "/textures/dial-guard_Bake1_PBR_Roughness.png"
  );
  //dial washers tex
  const dialWashersDiffuse = useTexture(
    "/textures/dial-washers_Bake1_PBR_Diffuse.png"
  );
  const dialWashersNormal = useTexture(
    "/textures/dial-washers_Bake1_PBR_Normal.png"
  );
  const dialWashersRoughness = useTexture(
    "/textures/dial-washers_Bake1_PBR_Roughness.png"
  );
  //dials tex
  const dialsDiffuse = useTexture("/textures/dials_Bake1_PBR_Diffuse.png");
  const dialsNormal = useTexture("/textures/dials_Bake1_PBR_Normal.png");
  const dialsRoughness = useTexture("/textures/dials_Bake1_PBR_Roughness.png");
  //screen housing tex
  const screenHousingDiffuse = useTexture(
    "/textures/screen-housing_Bake1_PBR_Diffuse.png"
  );

  useEffect(() => {
    bodyDiffuse.flipY = false;
    bodyDiffuse.needsUpdate = true;
    bodyNormal.flipY = false;
    bodyNormal.needsUpdate = true;
    bodyRoughness.flipY = false;
    bodyRoughness.needsUpdate = true;
    // screenHousingDiffuse.flipY = false;
    // screenHousingDiffuse.needsUpdate = true;
    // screenHousingNormal.flipY = false;
    // screenHousingNormal.needsUpdate = true;
    // screenHousingRoughness.flipY = false;
    // screenHousingRoughness.needsUpdate = true;
  }, []);

  return (
    <group
      {...props}
      position={[0, -4, -2]}
      rotation={[0, Math.PI * 1.8, 0]}
      dispose={null}
    >
      <mesh
        geometry={nodes["dial-washers_Baked"].geometry}
        material={nodes["dial-washers_Baked"].material}
      >
        <meshStandardMaterial
          map={dialWashersDiffuse}
          normalMap={dialWashersNormal}
          roughnessMap={dialWashersRoughness}
        />
      </mesh>
      <mesh
        geometry={nodes.body_Baked.geometry}
        material={nodes.body_Baked.material}
      >
        <meshStandardMaterial
          map={bodyDiffuse}
          normalMap={bodyNormal}
          roughnessMap={bodyRoughness}
        />
      </mesh>
      <mesh
        flatShading={false}
        geometry={nodes["screen-housing_Baked"].geometry}
        material={nodes["screen-housing_Baked"].material}
      >
        <meshPhongMaterial
          // flatShading={false}
          map={screenHousingDiffuse}
          // normalMap={screenHousingNormal}
          // roughnessMap={screenHousingRoughness}
        />
      </mesh>
      <mesh
        geometry={nodes.screen_Baked.geometry}
        material={nodes.screen_Baked.material}
        position={[0, 0, 0.032]}
      />
      <mesh geometry={nodes["access-panel_Baked"].geometry}>
        <meshStandardMaterial
          map={accessPanelDiffuse}
          normalMap={accessPanelNormal}
          roughnessMap={accessPanelRoughness}
        />
      </mesh>
      <mesh
        geometry={nodes.aerial_Baked.geometry}
        material={nodes.aerial_Baked.material}
        position={[0.148, 0, 0]}
      >
        <meshStandardMaterial
          map={aerialDiffuse}
          normalMap={aerialNormal}
          roughnessMap={aerialRoughness}
        />
      </mesh>
      <mesh
        geometry={nodes["button-bottom_Baked"].geometry}
        material={nodes["button-bottom_Baked"].material}
      >
        <meshStandardMaterial
          map={buttonBottomDiffuse}
          normalMap={buttonBottomNormal}
          roughnessMap={buttonBottomRoughness}
        />
      </mesh>
      <mesh
        geometry={nodes["button-top_Baked"].geometry}
        material={nodes["button-top_Baked"].material}
      >
        <meshStandardMaterial
          map={buttonTopDiffuse}
          normalMap={buttonTopNormal}
          roughnessMap={buttonTopRoughness}
        />
      </mesh>
      <mesh
        geometry={nodes["buttons-channel_Baked"].geometry}
        material={nodes["buttons-channel_Baked"].material}
      >
        <meshStandardMaterial
          map={buttonsChannelDiffuse}
          normalMap={buttonsChannelNormal}
          roughnessMap={buttonsChannelRoughness}
        />
      </mesh>
      <mesh
        geometry={nodes["dial-guard_Baked"].geometry}
        material={nodes["dial-guard_Baked"].material}
      >
        <meshStandardMaterial
          map={dialGuardDiffuse}
          normalMap={dialGuardNormal}
          roughnessMap={dialGuardRoughness}
        />
      </mesh>
      <mesh
        geometry={nodes.dials_Baked.geometry}
        material={nodes.dials_Baked.material}
      >
        <meshStandardMaterial
          map={dialsDiffuse}
          normalMap={dialsNormal}
          roughnessMap={dialsRoughness}
        />
      </mesh>
      <mesh
        geometry={nodes["aerial-holder_Baked"].geometry}
        material={nodes["aerial-holder_Baked"].material}
        position={[1.55, 4.6, -3.616]}
        scale={[0.155, 0.531, 0.155]}
      >
        <meshStandardMaterial
          map={aerialHolderDiffuse}
          normalMap={aerialHolderNormal}
          roughnessMap={aerialHolderRoughness}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/tele.glb");
